// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJ2xcPBlU7uZUey6BrXmAjUGiUhH7l-zU',
    appId: '1:908868416375:web:4ca142477559b9f1432772',
    messagingSenderId: '908868416375',
    projectId: 'research-143',
    authDomain: 'research-143.firebaseapp.com',
    databaseURL: 'https://research-143-default-rtdb.firebaseio.com',
    storageBucket: 'research-143.appspot.com',
    measurementId: 'G-0HXLSE73SL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWMWqma2qXQ1fUul4dxM1w6xYL6sCAsSk',
    appId: '1:908868416375:android:cfdf86f941d95825432772',
    messagingSenderId: '908868416375',
    projectId: 'research-143',
    databaseURL: 'https://research-143-default-rtdb.firebaseio.com',
    storageBucket: 'research-143.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbqiX1mEjB8Mjut4AMczXkRANRlGFF-6w',
    appId: '1:908868416375:ios:c1716b8c4544a9f1432772',
    messagingSenderId: '908868416375',
    projectId: 'research-143',
    databaseURL: 'https://research-143-default-rtdb.firebaseio.com',
    storageBucket: 'research-143.appspot.com',
    iosBundleId: 'com.finalproject.iot',
  );
}
